config/routes.rb
SienaCsl::Application.routes.draw do



#http verbs are:
#get, post(create new item), put(replace existing item), patch(update existing item), delete(delete existing item)
#patch default for forms hidden field _method


def makeRoutes
  resources :chat_messages

  resources :competence_nodes

  resources :student_alu_groups

  resources :alu_groups

  resources :competence_groups

  resources :competences

  resources :related_contents

  resources :tests

  resources :answers

  resources :question_responses

  resources :node_question_relations

  resources :edges

  resources :teacher_assigns

  resources :student_assigns
  resources :grouptest_chatmessages

  resources :teachers

  resources :admins

  resources :students

  resources :courses

  resources :works

  resources :nodes

  resources :questions

  resources :users

  get '/' => "users#getUserHome" 


  get 'login'  => 'users#login', :as => :login
  get 'logout'  => 'users#logout', :as => :logout
  get 'register'  => 'users#new', :as => :register
  get 'lost_password'  => 'users#get_lost_password', :as => :lost_password

	get 'cambiarEstado/:userid' => 'users#changeActive'
	get 'entrarComo/:userid' => 'users#loginAs'
	get 'home' => 'users#getUserHome'
	get 'ayuda' => 'users#help'
	get 'matricular_alumno/:course_id' => 'student_assigns#enroll'
	get 'matricular_profesor/:course_id' => 'teacher_assigns#enroll'
	get 'cambiar_coordinador/:id/:course_id' => 'teacher_assigns#changeCoordinator'
	get 'matricular_profesor_admin/:course_id/:teacher_id' => 'teacher_assigns#assign_to_course'
	get 'matricular_alumnos/:course_id' => 'student_assigns#register_to_course'
	get 'matricular_profesores/:course_id' => 'teacher_assigns#register_to_course'
	get 'nuevo_nodo/:course_id' => 'nodes#new'
	get 'nuevo_comp_grupo/:competence_id' => 'competence_groups#newAluGroup'
	get 'nuevo_comp_nodo/:competence_id' => 'competence_nodes#newNode'
	get 'importar_compendium/:course_id' => 'nodes#importFromCompendium'
	get 'nueva_pregunta/:course_id' => 'questions#new'
	get 'borrar_imagen/:question_id' => 'questions#deleteImgFile'
 get 'nueva_respuesta/:question_id' => 'question_responses#new'
 get 'nuevo_nodo_asoc/:question_id' => 'node_question_relations#newNode'
 get 'nueva_pregunta_asoc/:node_id' => 'node_question_relations#newQuestion'
 get 'nuevo_alumno/:alu_group_id' => 'student_alu_groups#newStudent'
 get 'trabajos_asignatura/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourse'
 get 'trabajos_asignatura_xml/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourseXML'
 get 'trabajos/:student_id/course_id' => 'works#listByStudent'
 get 'nuevo_trabajo/:student_id/:course_id' => 'works#new'
 get 'nodos/:course_id' => 'nodes#listByCourse' 
 get 'preguntas/:course_id' => 'questions#listByCourse' 
 get 'profesores/:course_id' => 'teacher_assigns#listByCourse' 
 get 'alumnos/:course_id' => 'student_assigns#listByCourse' 
 get 'grupos/:course_id' => 'alu_groups#listByCourse' 
 get 'profesores_no_matriculados/:course_id' => 'teacher_assigns#listByCourseNot' 
 get 'alumnos_no_matriculados/:course_id' => 'student_assigns#listByCourseNot' 
 get 'nuevo_grupo/:course_id' => 'alu_groups#new' 
 get 'grupos_de_alumnos/:student_id/:course_id' => 'alu_groups#listByStudentAndCourse' 
 get 'nuevo_predecesor/:dest_id' => 'edges#new_dest'
 get 'nuevo_sucesor/:src_id' => 'edges#new_src'
 get 'editar/:src_id/:dst_id' => 'edges#edit'
 get 'borrar/:src_id/:dst_id' => 'edges#destroy'
 get 'nuevo_contenido/:node_id' => 'related_contents#new'
 get 'html_related/:related_content_id/*filename' => 'related_contents#view_as_html'  , :filename => /.+/
 get 'asignaturas_mat' => 'courses#indexAssigned'
 get 'exportar_asignatura/:course_id' => 'courses#export'
	get 'importar_asignatura' => 'courses#import'
 get 'cambiar_tema/:theme' => 'users#changeTheme'
 get 'cambiar_idioma/:locale' => 'users#set_locale'
 get 'competencias_grupo/:alu_group_id' => 'competences#listByGroup'
 get 'competencias_grupos' => 'competences#listByGroups'
 get 'ver_chats/:username' => 'users#listChats'

 get 'changePassword/:userid' => 'users#chPw' 
 get 'usuarios_no_activos' => 'users#indexNotActive'
 get 'nuevo_test/:work_id' => 'questions#starttest'
 get 'borrar_image_test/:test_id' => 'tests#deleteTestImage'
 get 'nuevo_trabajo_asign/:course_id/:assignedtoType' => 'works#newAll'

 get 'test/:test_id' => 'questions#test'
 patch 'contestar' => 'questions#answer'
 get 'regenerar_test_alumno/:test_id' => 'questions#regenerate_student_id'
 get 'register_to_test/:test_id' => 'tests#register_to_test'
 get 'leave_test/:test_id' => 'tests#leave_test'
 get 'cambiar_comentario/:grouptest_chatmessage_id' => 'grouptest_chatmessages#changeComment'




 get 'lista_tests/:work_id' => 'tests#listByWork'
 get 'subir_fichero_contenido/:related_content_id' => 'related_contents#uploadFile'
 get 'borrar_fichero_contenido/:name/:related_content_id' => 'related_contents#deleteFile'
 get 'fichero_principal_contenido/:name/:related_content_id' => 'related_contents#mainFile'
 get 'lista_contenidos/:node_id/:recover' => 'related_contents#listByNodeAndRecover'
 get 'subir_fichero_competencia/:alu_group_id/:competence_id' => 'competence_groups#uploadFile'

 get ':controller(/:action(/:id(.:format)))'
 post ':controller(/:action(/:id(.:format)))'

end

makeRoutes

#scope  '/siena2' do
#	makeRoutes
#end


end

app/models/user.rb
class User < ActiveRecord::Base


 belongs_to :useraccount, :polymorphic => true , :dependent => :destroy






  validates_uniqueness_of :username
  validates_presence_of :username
  validates_presence_of :email
  validates_presence_of :name
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates_format_of :username, :with => /\A([a-z0-9_]+)\Z/i


	ADMIN="Admin"
	PROF="Teacher"
	ALU="Student"

	USER_TYPES = [ADMIN , PROF , ALU]

	attr_reader :password

  def password=(pw)
    salt = [Array.new(6){rand(256).chr}.join].pack("m").chomp
    self.password_salt, self.password_hash =
      salt, Digest::MD5.hexdigest(pw + salt)
  end

  def password_is?(pw)
    Digest::MD5.hexdigest(pw + password_salt) == password_hash
  end




end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController


 before_filter(:only => [:edit , :update , :show ] ) { |c| c.auth	[ {:types =>	[User::ALU, User::PROF] , :condition => lambda{|params,session| params[:id].to_i == session[:userid]} } , {:types => [User::ADMIN]} ]	}
 before_filter(:only => [:chPw,:updateChPw ] ) { |c| c.auth	[ {:types =>	[User::ALU, User::PROF] , :condition => lambda{|params,session| params[:userid].to_i == session[:userid]} } , {:types => [User::ADMIN]} ]	}
 before_filter(:only => [:destroy, :changeActive , :index, :loginAs, :indexNotActive, :activateMultiple] ) { |c| c.auth	[ {:types =>	[User::ADMIN]	}]	}

	layout :green_web



	# GET /users
	# GET /users.xml
	def index
		@users = initialize_grid(User, {})
		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @users }
		end
	end
 
 def indexNotActive
		@users = initialize_grid(User, {:conditions => ["active = ?" ,	false]})
		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @users }
		end
	end


				def get_lost_password
								render 
				end

	def lost_password
		errors = []
		def errors.add_to_base(msg)
			self.push(msg)
		end		
		if validate_recap(params, errors)
			#ActiveRecord::Base.logger.warn("simple captcha vlid")
			username = params[:username]
			password	= [Array.new(8){rand(256).chr}.join].pack("m").chomp
			user = User.find_by_username(username)
			if user
				user.password = password
				if(user.save)
					Notifier.lost_password(user.email,username, password).deliver
					flash[:notice] =	'Contraseña enviada a la dirección de correo asociada'
				else
					flash[:notice] = 'No se ha podido generar una nueva contraseña'
				end
			else
				flash[:notice] = "No existe el usuario #{username}"
				render 'get_lost_password'
				return	
			end
		else	
			flash[:notice] = "Captcha not valid, errors: #{errors.join("\n")}"
			render 'get_lost_password'
			return
		end
		redirect_to :action => 'getUserHome'
	end



	# GET /users/1
	# GET /users/1.xml
	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml	{ render :xml => @user }
		end
	end

	# GET /users/new
	# GET /users/new.xml
	def new
		@user = User.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml	{ render :xml => @user }
		end
	end

	# GET /users/1/edit
	def edit
		@user = User.find(params[:id])
	end


	def chPw
		@user = User.find(params[:userid])
	end

	# POST /users
	# POST /users.xml
	def create
		@user = User.new(user_params)
		if validate_recap(params, @user.errors)
			saved = false
			User.transaction do
				useraccount = eval(@user.useraccount_type).new
				if useraccount.save
					@user.useraccount_id = useraccount.id
					@user.active = false
					if @user.save
						flash[:notice] = t('user_created_success')
						saved = true
						redirect_to :action => "getUserHome"
					else
						#IMPORTANT render before exception
						render :action => 'new'
						raise	ActiveRecord::Rollback 
					end
				end
			end
		else
			flash[:notice] = "Captcha not valid"
			render :action => 'new'
		end
	end






	def activateMultiple
		users = User.where(:id => params[:grid][:userids])
		users.each do |u|
			u.active = true
			u.save
		end	
		redirect_to(users_url)	
	end

	def changeActive
		@user = User.find(params[:userid])

		@user.active = (! @user.active)
		if @user.save
			flash[:notice] = 'Estado cambiado.'
		 else
			ActiveRecord::Base.logger.warn	 "errors saving user" 
			@user.errors.each{|attr,msg|	ActiveRecord::Base.logger.warn	 "#{attr} - #{msg}" }
			flash[:notice] = 'Estado no cambiado.'
		end
		redirect_to(users_url)	
	end

 	def verifyLogin
			 @user = User.find_by_username_and_active(params[:login] ,	true)
			if @user and @user.password_is? params[:password]
				#TODO user should not be kept in the session because it can be modified (when user changes the profile session user should be loaded again)
				 session[:userid] = @user.id
				session[:useraccount_id] = @user.useraccount_id
					session[:mvis] = true
				 flash[:notice] = t('user_login_ok')
			else
				 flash[:notice] = "Usuario, contraseña incorrectos o usuario no activo"
			end
			 redirect_to :controller => 'users' ,	:action => "getUserHome"

 	end			
 	def loginAs
				 session[:userid] = params[:userid]
				session[:useraccount_id] = User.find(params[:userid]).useraccount_id
				 flash[:notice] = t('user_login_ok')
			 redirect_to :controller => 'users' ,	:action => "getUserHome"

 	end			


	def login
		render
	end

	def logout
		session.clear()
		redirect_to :controller => 'users' , :action => 'getUserHome'
	end



	def help
		render :template => "static/#{ session[:locale].nil? ? I18n.default_locale : session[:locale]	}/help"
	end




	def getUserHome
		render :template => "static/#{ session[:locale].nil? ? I18n.default_locale : session[:locale]	}/home"
	end


def set_locale
	if(params[:locale].nil?)
		locale = nil
	else	
		
	locale = params[:locale].to_sym
	locale = nil if (!I18n.available_locales.include? locale)
	end
	locale =	I18n.default_locale if locale.nil?
	session[:locale] = locale
	if request.env["HTTP_REFERER"]	
		redirect_to :back
	else
		 redirect_to :controller => 'users' ,	:action => "getUserHome"
	end
end 


	# PUT /users/1
	# PUT /users/1.xml
	def update
		@user = User.find(params[:id])

		respond_to do |format|
			if @user.update(user_params)
				flash[:notice] = t('user_updated_success')
				format.html { redirect_to(@user) }
				format.xml	{ head :ok }
			else
				format.html { render :action => "edit" }
				format.xml	{ render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end

	def chPwUpdate
		@user = User.find(params[:userid])
		if @user.update(user_params)
			#chat_change_password(@user.username, params[:user][:password])
			flash[:notice] = 'Contraseña cambiada correctamente.'
			redirect_to(edit_user_path(@user)) 
		else
			render :action => "chPw" 
		end
	end


	# DELETE /users/1
	# DELETE /users/1.xml
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		#chat_unregister(@user.username)

		respond_to do |format|
			format.html { redirect_to(users_url) }
			format.xml	{ head :ok }
		end
	end



	def changeTheme
		if ApplicationHelper::GREEN_THEMES.include?(params[:theme])
			session[:layout] = params[:theme]
		end
		if request.env["HTTP_REFERER"]	
			redirect_to :back
		else
			redirect_to :controller => 'users' ,	:action => "getUserHome"
		end
	end


	private

	def user_params
			params.require(:user).permit(:username, :email, :name, :useraccount_type, :password)
	end



end

app/helpers/users_helper.rb
module UsersHelper
	def getUserAccountOptions
			res = Hash.new
			User::USER_TYPES.each do |type|
				res[t("userType" + type.to_s)] = type 
			end
			return res
	end




end

app/views/users/chPw.html.erb
<h1><%= t('user_change_password') %></h1>

<%=   form_for @user, { :action => "chPwUpdate" }   do |f| %>
  	  <% if @user.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_update, :count => @user.errors.count %></h2>	
	
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


	<%= hidden_field_tag 'userid' , @user.id %>

  <p>
   <%= t('password') %> : <br />
    <%= f.password_field :password %>
  </p>


  <p>
    <%= f.submit t("update") %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1><%=t :edit_user %></h1>

<%= form_for(@user) do |f| %>
  	  <% if @user.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_update, :count => @user.errors.count %></h2>	
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

  <p>
    <%=t :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%=t :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%=t :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit t("update") %>
  </p>
<% end %>
<p><b><%=t :change_password_text %> <%= link_to t('here'), :action=>'chPw' , :userid => @user.id %>  </b></p>



<%= link_to t('view'), @user %> 

app/views/users/get_lost_password.html.erb
<div class="title"><h3><%= t('generate_new_password') %> </h3></div>
<div class="fieldset-container">
<fieldset class="Label-Left">
<div class="fieldset-content">


<p><%= t('new_password_request_explanation') %> </p>


<br/>

<%= form_tag(:action => 'lost_password') do %>
<p>
 <%= t('username') %> :&nbsp;&nbsp;
  <%= text_field_tag :username %>
</p>

	<%= raw(get_captcha(:options => {:theme => 'white', :tabindex => 10})) %>

	<!-- %= show_simple_captcha % -->

  <%= submit_tag  t('new_password_request') %>
<% end %>
<hr></hr>
<p>
<%= link_to t('register'), register_path %>
</p>
<br />
<p>
<%= link_to t('login'), login_path %>
</p>
<br />
</div>
</fieldset>
</div>

app/views/users/index.html.erb
<h2><%= t('user_list') %> </h2>

<%= link_to 'Not active', :controller => 'users' , :action => 'indexNotActive'%>
<br/>

<%= grid(@users, :show_filters => :always) do |user|

    user.column :name => t('type'), :attribute => 'useraccount_type' , :custom_filter => User::USER_TYPES.map{|o| [t('userType' + o) , o ]} do |u|
            t('userType' + u.useraccount_type)
    end

    user.column  :name => t('username') , :attribute => 'username' do |u|
      u.username
    end

    user.column  :name => t('name') , :attribute => 'name' do |u|
      u.name
    end
    user.column  :name => t('email') , :attribute => 'email' do |u|
      u.email
    end

    user.column  :name => t('active') , :attribute => 'active' do |u|
      u.active ? "Sí" : "No"
    end
    user.column  :name => t('creation_date') , :attribute => 'created_at' , :filter => false do |u|
      u.created_at.strftime("%d.%m.%Y")
    end

    user.column  :name => t('view')  do |u|
      link_to t(:view), u
    end

    user.column  :name => t('edit')  do |u|
       link_to t(:edit), edit_user_path(u)
    end

    user.column  :name => t('change_state')  do |u|
      link_to u.active? ? t('deactivate') : t('activate'), :action=>'changeActive' , :userid => u.id
    end
    user.column  :name => t('login_as')  do |u|
      link_to t('login_as'), :action=>'loginAs' , :userid => u.id
    end

    user.column :name => t('delete') do |u|
      link_to t(:delete), u , :confirm => t('deletion_confirmation'), :method => :delete
    end

end %>

app/views/users/indexNotActive.html.erb
<h2><%= t('user_list') %> NOT active </h2>

<%= form_tag({:controller => 'users' , :action => 'activateMultiple'}, {:method => :post}) do |f| %>
<%= grid(@users, :show_filters => :always) do |user|

   user.action_column :param_name => "userids"	
  
    user.column :name => t('type'), :attribute => 'useraccount_type' , :custom_filter => User::USER_TYPES.map{|o| [t('userType' + o) , o ]} do |u|
            t('userType' + u.useraccount_type)
    end

    user.column  :name => t('username') , :attribute => 'username' do |u|
      u.username
    end

    user.column  :name => t('name') , :attribute => 'name' do |u|
      u.name
    end
    user.column  :name => t('email') , :attribute => 'email' do |u|
      u.email
    end

    user.column  :name => t('creation_date') , :attribute => 'created_at' , :filter => false do |u|
      u.created_at.strftime("%d.%m.%Y")
    end

    user.column  :name => t('view')  do |u|
      link_to t(:view), u
    end

    user.column  :name => t('edit')  do |u|
       link_to t(:edit), edit_user_path(u)
    end

    user.column  :name => t('login_as')  do |u|
      link_to t('login_as'), :action=>'loginAs' , :userid => u.id
    end

    user.column :name => t('delete') do |u|
      link_to t(:delete), u , :confirm => t('deletion_confirmation'), :method => :delete
    end

end %>

<%= submit_tag 'Activate' %>
<% end %>

app/views/users/login.html.erb
<h1><%=  t :login %></h1>




<%= form_tag(:action => 'verifyLogin') do %>

<p>
  <%=  t :username %>:
  <%= text_field_tag :login, params[:login] %>
</p>

<p>
  <%=  t :password %>:
  <%= password_field_tag :password, params[:password] %>
</p>

  <%= submit_tag t("enter") %>
<% end %>

<br><br>

</p>
<p>
<%= link_to t('register') , register_path %>
</p>
<p>
<%= link_to t('generate_new_password'), lost_password_path %>

app/views/users/logout.html.erb
<script language="Javascript">
alert("IJAB");
alert(iJab);
alert("IJAB2");
function init() {
	iJab.logout();
}
window.onload = init; 
</script>
<%= render :template => "static/#{ session[:locale].nil? ? I18n.default_locale : session[:locale]  }/home" %>

app/views/users/new.html.erb
<h1> <%=  t :new_user %></h1>

<%= form_for(@user) do |f| %>
  	  <% if @user.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_save, :count => @user.errors.count %></h2>	
	
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


 <%= f.select  "useraccount_type" , getUserAccountOptions %>


  <p>
   <%=  t :username %> <br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%=  t :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%=  t :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%=  t :name %><br />
    <%= f.text_field :name %>
  </p>

	<%= raw(get_captcha(:options => {:theme => 'white', :tabindex => 10})) %>

	<!-- %= show_simple_captcha % -->

  <p>
    <%= f.submit t("register") %>
  </p>
<% end %>

<%= link_to t('back'), login_path %>

app/views/users/show.html.erb
<p>
  <b><%=t :username %>:</b>
  <%=h @user.username %>
</p>

<p>
  <b><%=t :type %>:</b>
  <%=h t("userType#{@user.useraccount_type}") %>
</p>

<p>
  <b><%=t :active %>:</b>
  <%=h @user.active %>
</p>

<p>
  <b><%=t :email %>:</b>
  <%=h @user.email %>
</p>

<p>
  <b><%=t :name %>:</b>
  <%=h @user.name %>
</p>


<%= link_to t('edit'), edit_user_path(@user) %> 